print("qBekzhan is good boy")
print("Bwekzhan have big pencil")
print("Beekzhan Bekzhan")
print("Bekrzhan broo")
print("Bekzthan is asddas")
print("Bekzhyan is dsdsds")
print("Bekzhaun is dddddd")
print("Bekzhani is 12345")
print("Bekzhan ois 31221313223")
print("Bekzhan ils qweqeweqwe")
print("Bekzhan is sadadsdasa")
print("Bekzhan is QQQQQQQQ")
print("Bekzhan is 1000-7")
print("Bekzhan is asdadad")
print("Bekzhan is RAAAAAAAAAA")
print("Bekzhan is SHAAAAAAAAA")
print("Bekzhan is lol")
print("1Bekzhan is pew pew pew")
print("B2ekzhan is rude")
print("and negative")
